<a href="https://colab.research.google.com/github/Movya777/Model-Building/blob/main/Naive_Baye's_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🤖 **Naive Bayes Classifier: Unleashing the Power of Probability!**

Ever wondered how email spam filters work? Or how a model can classify sentiments in a tweet?

Meet Naïve Bayes—a fast, efficient, and surprisingly powerful classification algorithm based on Bayes' Theorem!

In this project, I implemented a Naïve Bayes classifier to predict the type of flower with astonishing accuracy! 🎯

### Dataset Information 📁
**Iris dataset** imported from sklearn library

It is one of the most well-known datasets in the world of machine learning and data science It consists of 150 records of Iris flowers, including information about their sepal and petal length and width, as well as the type of Iris flower.
#### Features:
- Sepal Length
- Sepal width
- Petal length
- Petal width

Output: Type of Iris flower


In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Naive Bayes
from sklearn.naive_bayes import GaussianNB

#performance metrics
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
X,y=load_iris(return_X_y=True)

In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [4]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

All the features are continuous, so Guassian Naive Bayes should be used for classfication

In [9]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)

#prediction
y_pred_gnb=gnb.predict(X_test)
print("Accuracy:\n", accuracy_score(y_pred_gnb,y_test))
print("Classification Report:\n", classification_report(y_pred_gnb,y_test))
print("Confusion Matrix:\n", confusion_matrix(y_pred_gnb,y_test))

Accuracy:
 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


Since the datset is so small, Gaussian Naive Baye's found be giving 100% accuracy.
